### ISSUE TITLE
Problem with automatic data submission in VP calculator

### ISSUE THREAD

**Issue by mao-liu** [johnnybainguyen/BoomBeachStatistics#1]
Where user enters both XP and VP, the entry is saved in the database via insertXPVPCollection. The page then returns "Sorry, no data found for the given XP".

Two suggestions:
1. Change line 93 of `app.js`: so that the `!vp` criteria is removed. Where VP and XP are both submitted, a search will be always be conducted.
2. There should be a "sandbox mode", where the user can enter fictitious values to experiment with the calculator without adding to the real database. Perhaps a checkbox saying "this is not a real score", which is off by default.

Also, if a user searches one set of IP/VP multiple times, will this register as multiple entries in the database? Duplication can skew statistics.

**Comment by johnnybainguyen** [comment]
Thanks!  

Forgot to take that out.  

1) Fixed.  Removed !vp

2) I made changes to the template, and added the word "Optional"  for the vp field.  So users can just type in XP and play around with it.

Last Part: I do an upsert everytime I insert into database.  So if there is a match for IP, XP, and VP, I throw it out.  If there is a match for IP and XP only, then it adds a new one.

**Comment by johnnybainguyen** [comment]
I was going to do another view template for when the user inputs VP which includes histogram, bell chart, standard deviations.  More statistical stuff hence the !vp.  Something special if they give me their VP!  Sort of not motivated right now to do that

**Comment by ch41rmn** [comment]
Nice fixes.

I was that reddit guy who was asking about charts/etc. I just forked the repo, will start playing with it over the coming week.

Re. charts/stats, here is what I have in mind:

- XP is supplied, return box plot or distribution plot of VPs for the XP

- VP is supplied, select a VP range (according to Daily Rewards definition), return box plot or distribution plot of XPs for the VP range

- XP and VP are supplied, here we have the option of returning a scatter plot or contour plot.

**Comment by johnnybainguyen** [comment]
Sounds great!  Cant wait to see it.  As long as we keep it simple for users especially user input.  I'm happy.

**Comment by johnnybainguyen** [comment]
Sort of running out of stuff to do on the site as the site is nearing its completion.  I'm starting to work on the graph.  Just giving you a heads up just in case I can work with what you have so far.
